### ISSUE TITLE
it works

### ISSUE THREAD

**Issue by Runaway1956** [T2minator/mbp-tails#1]
I just wanted to leave a word of praise, don't know any other means.  I've been booting my 2019 MacBook Pro 16" with every ISO I can find - Fedorambp installs for me, but has issues, other mbp ISO mostly just fail.  Not only does your TAILS boot up, but everything that you promise will work actually works.  Most surprising thing is - TOR browser works well, it works fast, and I'm loving it.  TOR is noTORiously slow for browsing, but not with your ISO.  Great job!

**Comment by T2minator** [comment]
**T2Tails - "It's not just you and a random raccoon in Wisconsin!"**

I've let the repo slip a few months, but the instructions remain relevant for ongoing Tails updates. Anyone can let me know if instructions are starting to fail, but I'm likely to check in and verify again any month now. Thanks for the kind comment!
