### ISSUE TITLE
5.3.1 attempt fails at update-intramfs

### ISSUE THREAD

**Issue by akda5id** [T2minator/mbp-tails#2]
Decided to give it a shot with 5.3.1, all went well until `dpkg -i linux-image-*.deb`.
Error was:
>I: update-initramfs is disabled (live system is running without media mounted on /run/live/medium).

**Comment by akda5id** [comment]
I blindly changed
```
sudo mkdir -p squashfs-root/lib/live/mount/medium && \
sudo mount --bind /lib/live/mount/medium squashfs-root/lib/live/mount/medium
```
to
```
sudo mkdir -p squashfs-root/run/live/medium && \
sudo mount --bind /lib/live/mount/medium squashfs-root/run/live/medium
```
And it seems like it may have worked? I.e. there are now new initrd.img and vmlinuz next to the .bak's in `/lib/live/mount/medium/live`

Edit: And this was able to create a bootable USB following the remainder of the instructions. No idea if what I did is correct, but does seem to work.

**Comment by T2minator** [comment]
Yep, precisely that! I've just updated the instructions for the latest Tails. A couple other minor but important changes are all implemented.
